# out line code for the run this file is not being used
# i eneded up using GIT from the web browser 

name: Docker Image CI

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t WZRD95/DEMO_Liatrio:latest
    - name: publish
      run: docker push WZRD95/DEMO_Liatrio:latest

