name: Docker Image CI

on:
  [workflow-dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t WZRD95/DEMO_Liatrio:latest
    - name: publish
      docker push WZRD95/DEMO_Liatrio:latest
