name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-test:$(date +%s)
    - name: Build the Docker image
      run: docker build . -t demo_liatrio/dockerfile:latest
    #- name: publish
    #  run: docker push demo_liatrio/dockerfile:latest
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

