name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v3
    - name: node
      uses: actions/setup-node@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-test:$(date +%s)
    - name: Build the Docker image
      run: docker build -t my-image .
    #- name: publish
    #  run: docker push demo_liatrio/dockerfile:latest
    - name: Run Docker container
      run: docker run -p 80:80 -d --name demo-disk my-image
    - name: See if its running 
      run: docker ps 
    - name: ping
      run: ping localhost
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

