name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PORT: 80
      LOOKFOR: ${{ secrets.TEST_04 }}
      
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t ${{ secrets.TEST_01 }} .
    - name: Run Docker container
      run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
    - name: See if its running 
      run: docker ps 
    - name: Run Tests
      uses: liatrio/github-actions/apprentice-action@apprentice-action-update



