name: Docker Image CI

on: workflow_dispatch

jobs:

  Build:
    runs-on: ubuntu-latest
    env:
      PORT: 80
      LOOKF: ${{ secrets.TEST_04 }}
      LOOKFO: ${{ secrets.TEST_05 }}
      LOOKFOR: ${{ secrets.TEST_06 }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
  DockerBuild:
    name: To Docker 
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.TEST_11 }}
          password: ${{ secrets.TEST_07 }}
      - name: Build the Docker image
        run: docker build -t ${{ secrets.TEST_01 }} .
      - name: Run Docker container
        run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
      - name: See if its running 
        run: docker ps
        
    #- name: Run Tests
    #  uses: liatrio/github-actions/apprentice-action@e76be8947a5e374b5588c00e3f4b3f4d4dbe5ecc
    #- name: Run Tests
    #  uses: actions/checkout@v4
    #  with: 
    #    repository: wzrd95/its_a_secrect@main
    #    token:  ${{secrets.TEST_20}}
    #    path: ./.github/actions/its_a_secrect
   # - name: Run action from private repo
    #  uses: ./.github/actions/its_a_secrect
    #- name: new try 
     # uses: wzrd95/its_a_secrect/action.yaml@4a9afff58468bc089923a31e0c0527e52a4ac6d0
    #- name: Run action from private repo
     # uses: wzrd95/its_a_secrect@main 
      #with: 
      #  token:  ${{secrets.TEST_20}}
  TestCodeMyRepo:
    name: Code test sent to my REPO
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: wzrd95/its_a_secrect@8ca9cf144862c2d677be09eed069587c6984474c
     # with:
      #  owner: wzrd95
    #    github_token:  ${{secrets.TEST_20}}
      #  workflow_file_name: action.yaml
   # - name: Run action from private repo
  #    uses: ./.github/its_a_secrect@main
  PushToDocker:
    name: To MY Docker Hub
    needs:  TestCodeMyRepo
    runs-on: ubuntu-latest
    steps:
      - name: Send out
        run: |
          docker tag ${{ secrets.TEST_01 }}  ${{ secrets.TEST_12 }} 
          docker push ${{ secrets.TEST_12 }}:latest

