name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t wzrd95/demo_liatrio/dockerfile:latest
    - name: publish
      run: docker push wzrd95/demo_liatrio/dockerfile:latest

