name: Docker Image CI

on: workflow_dispatch

jobs:

  Build:
    runs-on: ubuntu-latest
    env:
      LOOKF: ${{ secrets.TEST_04 }}
      LOOKFO: ${{ secrets.TEST_05 }}
      LOOKFOR: ${{ secrets.TEST_06 }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
  DockerBuild:
    name: Docker Test Build
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up envorment 
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t ${{ secrets.TEST_01 }} .
      - name: Run Docker container
        run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
      - name: See if its running 
        run: docker ps

  TestCodeMyRepo:
    name: Code test wth my REPO
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:
      - name: Set up envorment 
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t ${{ secrets.TEST_01 }} .
      - name: Run Docker container
        run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
      - name: Run Tests
        uses: wzrd95/its_a_secrect@8ca9cf144862c2d677be09eed069587c6984474c

  TestCodeOld:
    name: Test Liatrio @ OLD
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:
      - name: Set up envorment 
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t ${{ secrets.TEST_01 }} .
      - name: Run Docker container
        run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
      - name: See if its running 
        run: docker ps
      - name: Run Tests
        uses: liatrio/github-actions/apprentice-action@e76be8947a5e374b5588c00e3f4b3f4d4dbe5ecc

  TestCodeMain:
    name: Test Liatrio @ MAIN
    continue-on-error: true
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:
      - name: Set up envorment 
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t ${{ secrets.TEST_01 }} .
      - name: Run Docker container
        run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
      - name: See if its running 
        run: docker ps
      - name: Run Tests
        uses: liatrio/github-actions/apprentice-action@master
  
  PushToDocker:
    name: Docker Push -->
    needs: TestCodeMyRepo
    runs-on: ubuntu-latest
    steps:
      - name: Set up envorment 
        uses: actions/checkout@v4
      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.TEST_11 }}
          password: ${{ secrets.TEST_07 }}
      - name: Build the Docker image
        run: docker build -t ${{ secrets.TEST_01 }} .
      - name: Run Docker container
        run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
      - name: Send out
        run: |
          docker tag ${{ secrets.TEST_01 }}  ${{ secrets.TEST_12 }} 
          docker push ${{ secrets.TEST_12 }}:latest

