name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PORT: 80
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Node
      uses: actions/setup-node@v3
    - name: Build the Docker image
      run: docker build -t my-image .
    - name: Run Docker container
      run: docker run -p 80:80 -d --name demo-disk my-image
    - name: See if its running 
      run: docker ps 
    - name: Run Tests
      uses: liatrio/github-actions/apprentice-action@master

