name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PORT: 80
      LOOKF: ${{ secrets.TEST_04 }}
      LOOKFO: ${{ secrets.TEST_05 }}
      LOOKFOR: ${{ secrets.TEST_06 }}
      
      
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.TEST_11 }}
        password: ${{ secrets.TEST_07 }}
    - name: Build the Docker image
      run: docker build -t ${{ secrets.TEST_01 }} .
    - name: Run Docker container
      run: ${{ secrets.TEST_03 }} ${{ secrets.TEST_02 }} ${{ secrets.TEST_01 }}
    - name: See if its running 
      run: docker ps 
    #- name: Run Tests
    #  uses: liatrio/github-actions/apprentice-action@e76be8947a5e374b5588c00e3f4b3f4d4dbe5ecc
    #- name: Run Tests
    #  uses: actions/checkout@v4
   #   with: 
   #     repository: wzrd95/its_a_secrect@main
   #     token:  ${{secrets.MY_TOKEN}}
 #      path: .github/its_a_secrect@main
  #  - name: Run action from private repo
#      uses: ./.github/its_a_secrect@main
    - name: new try 
      run: wzrd95/its_a_secrect@main
    
    - name: Send out
      run: |
        docker tag ${{ secrets.TEST_01 }}  ${{ secrets.TEST_12 }} 
        docker push ${{ secrets.TEST_12 }}:latest

